language: python

python:
  - "3.7"

before_install:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - source ~/miniconda3/bin/activate
  - conda update --yes conda
  - conda deactivate

install:
  - conda env create -f requirements.yml
  - conda activate snap-tb3

script:
  - python3 test.py  # will run all tests in the package
  - python3 test_output.py #Compare the output file and our saved one
